const categories = [
  {
    name: "Chairs",
    slug: "chairs",
    description: "Handcrafted wooden seating for indoor and outdoor comfort.",
    image: "/assets/crops/collection-chair.jpg",
    cardImage: "/assets/crops/collection-chair.jpg",
    isFeatured: true,
  },
  {
    name: "Beds",
    slug: "beds",
    description: "Classic and modern bed frames built from premium wood.",
    image: "/assets/crops/collection-bed.jpg",
    cardImage: "/assets/crops/collection-bed.jpg",
    isFeatured: true,
  },
  {
    name: "Tables",
    slug: "tables",
    description: "Dining, coffee and accent tables shaped with refined detailing.",
    image: "/assets/crops/collection-table.jpg",
    cardImage: "/assets/crops/collection-table.jpg",
    isFeatured: true,
  },
  {
    name: "Bookcases",
    slug: "bookcases",
    description: "Display-ready storage solutions for books, decor and keepsakes.",
    image: "/assets/crops/collection-table.jpg",
    cardImage: "/assets/crops/collection-table.jpg",
    isFeatured: false,
  },
  {
    name: "Cabinets",
    slug: "cabinets",
    description: "Rustic cabinets and sideboards for functional organization.",
    image: "/assets/crops/hotdeal-right-full.jpg",
    cardImage: "/assets/crops/hotdeal-right-full.jpg",
    isFeatured: false,
  },
  {
    name: "Boxes",
    slug: "boxes",
    description: "Utility trunks and decorative wooden storage boxes.",
    image: "/assets/crops/collection-table.jpg",
    cardImage: "/assets/crops/collection-table.jpg",
    isFeatured: false,
  },
];

const products = [
  {
    title: "Wave Lounge Chair",
    slug: "wave-lounge-chair",
    shortDescription:
      "Signature flowing lounge chair inspired by contemporary sculpture.",
    description:
      "The Wave Lounge Chair is designed with a fluid bent-wood silhouette that balances aesthetics and ergonomics. Its handcrafted structure creates a striking statement in living spaces while maintaining dependable comfort.",
    price: 129.99,
    compareAtPrice: 199.99,
    image: "/assets/crops/hero-chair.jpg",
    gallery: ["/assets/crops/hero-chair.jpg", "/assets/crops/collection-chair.jpg"],
    categorySlug: "chairs",
    stock: 12,
    tags: ["hero", "featured"],
    badge: "Hot",
    rating: 4.9,
    reviewCount: 184,
    specifications: [
      { label: "Material", value: "Steam-bent oak strips" },
      { label: "Finish", value: "Natural matte lacquer" },
      { label: "Weight Capacity", value: "130 kg" },
    ],
  },
  {
    title: "Aurora Round Center Table",
    slug: "aurora-round-center-table",
    shortDescription: "Compact artisan centerpiece with layered wood grain.",
    description:
      "A pedestal-style center table with an artistic base and circular top, ideal for conversation corners and modern lounge spaces.",
    price: 134.99,
    compareAtPrice: 164.99,
    image: "/assets/crops/obj-table-round.jpg",
    gallery: ["/assets/crops/obj-table-round.jpg"],
    categorySlug: "tables",
    stock: 17,
    tags: ["featured"],
    rating: 4.7,
    reviewCount: 69,
    specifications: [
      { label: "Material", value: "Layered teak veneer" },
      { label: "Diameter", value: "70 cm" },
    ],
  },
  {
    title: "Terra Low Coffee Table",
    slug: "terra-low-coffee-table",
    shortDescription: "Minimal low-rise coffee table with dark walnut finish.",
    description:
      "The Terra table complements contemporary seating with clean geometry and a broad platform for decor, books and trays.",
    price: 134.99,
    compareAtPrice: 154.99,
    image: "/assets/crops/obj-table-square.jpg",
    gallery: ["/assets/crops/obj-table-square.jpg"],
    categorySlug: "tables",
    stock: 19,
    tags: ["featured"],
    rating: 4.6,
    reviewCount: 41,
    specifications: [
      { label: "Material", value: "Walnut hardwood" },
      { label: "Dimensions", value: "120 x 70 x 34 cm" },
    ],
  },
  {
    title: "Harvest Folding Console",
    slug: "harvest-folding-console",
    shortDescription: "Convertible console with rustic cross-leg styling.",
    description:
      "Designed for adaptable spaces, this wooden console transitions from a narrow profile to a practical serving surface.",
    price: 134.99,
    compareAtPrice: 149.99,
    image: "/assets/crops/obj-table-fold.jpg",
    gallery: ["/assets/crops/obj-table-fold.jpg"],
    categorySlug: "tables",
    stock: 14,
    tags: ["featured"],
    rating: 4.6,
    reviewCount: 36,
    specifications: [
      { label: "Material", value: "Acacia wood" },
      { label: "Mechanism", value: "Fold-out leg frame" },
    ],
  },
  {
    title: "Olive Serving Bowl Set",
    slug: "olive-serving-bowl-set",
    shortDescription: "Nested handcrafted bowls for table styling and serving.",
    description:
      "A natural wood bowl set finished by hand to add warmth and texture to dining tables or open kitchen shelves.",
    price: 134.99,
    compareAtPrice: 149.99,
    image: "/assets/crops/obj-table-round.jpg",
    gallery: ["/assets/crops/obj-table-round.jpg"],
    categorySlug: "boxes",
    stock: 32,
    tags: ["featured"],
    rating: 4.8,
    reviewCount: 55,
    specifications: [
      { label: "Material", value: "Sustainably harvested wood" },
      { label: "Set", value: "4 nested bowls" },
    ],
  },
  {
    title: "Monarch Dining Chair",
    slug: "monarch-dining-chair",
    shortDescription: "Straight-back dining chair with traditional joinery.",
    description:
      "A reliable dining companion with upright support and precision-cut slats, crafted for daily use.",
    price: 134.99,
    compareAtPrice: 149.99,
    image: "/assets/crops/obj-chair-wood.jpg",
    gallery: ["/assets/crops/obj-chair-wood.jpg"],
    categorySlug: "chairs",
    stock: 21,
    tags: ["special"],
    rating: 4.5,
    reviewCount: 48,
    specifications: [
      { label: "Material", value: "Solid ash wood" },
      { label: "Seat Height", value: "46 cm" },
    ],
  },
  {
    title: "Cedar Garden Recliner",
    slug: "cedar-garden-recliner",
    shortDescription: "Outdoor-friendly recliner with wide armrests.",
    description:
      "A laid-back recliner built for patios, decks and balconies, featuring a naturally weather-resistant cedar body.",
    price: 134.99,
    compareAtPrice: 154.99,
    image: "/assets/crops/collection-chair.jpg",
    gallery: ["/assets/crops/collection-chair.jpg"],
    categorySlug: "chairs",
    stock: 16,
    tags: ["special"],
    rating: 4.7,
    reviewCount: 92,
    specifications: [
      { label: "Material", value: "Cedar wood" },
      { label: "Use", value: "Outdoor and indoor" },
    ],
  },
  {
    title: "Dune Accent Duo",
    slug: "dune-accent-duo",
    shortDescription: "Two-piece accent chair set for modern interiors.",
    description:
      "A compact duo of curved accent chairs designed to frame coffee tables and conversational seating zones.",
    price: 134.99,
    compareAtPrice: 149.99,
    image: "/assets/crops/collection-chair.jpg",
    gallery: ["/assets/crops/collection-chair.jpg"],
    categorySlug: "chairs",
    stock: 11,
    tags: ["special"],
    rating: 4.4,
    reviewCount: 27,
    specifications: [
      { label: "Set", value: "2 matching chairs" },
      { label: "Finish", value: "Warm oak stain" },
    ],
  },
  {
    title: "Rustik Trunk Chest",
    slug: "rustik-trunk-chest",
    shortDescription: "Low-profile chest with ample hidden storage.",
    description:
      "An elegant trunk chest that combines living-room utility with classic wood panel details.",
    price: 134.99,
    compareAtPrice: 144.99,
    image: "/assets/crops/collection-table.jpg",
    gallery: ["/assets/crops/collection-table.jpg"],
    categorySlug: "boxes",
    stock: 13,
    tags: ["special"],
    rating: 4.6,
    reviewCount: 38,
    specifications: [
      { label: "Material", value: "Engineered teak wood" },
      { label: "Storage", value: "Single deep compartment" },
    ],
  },
  {
    title: "Atlas Open Bookcase",
    slug: "atlas-open-bookcase",
    shortDescription: "Tall open bookcase with multi-shelf organization.",
    description:
      "Display books and collectibles in this vertically structured shelf system built for neat visual rhythm.",
    price: 134.99,
    compareAtPrice: 164.99,
    image: "/assets/crops/collection-table.jpg",
    gallery: ["/assets/crops/collection-table.jpg"],
    categorySlug: "bookcases",
    stock: 9,
    tags: ["popular"],
    rating: 4.7,
    reviewCount: 66,
    specifications: [
      { label: "Shelves", value: "8 fixed compartments" },
      { label: "Height", value: "200 cm" },
    ],
  },
  {
    title: "Sovereign Wood Bed",
    slug: "sovereign-wood-bed",
    shortDescription: "Classic wood-frame bed with elevated headboard profile.",
    description:
      "A timeless bedroom centerpiece featuring sturdy rails and handcrafted edge detailing.",
    price: 134.99,
    compareAtPrice: 184.99,
    image: "/assets/crops/collection-bed.jpg",
    gallery: ["/assets/crops/collection-bed.jpg"],
    categorySlug: "beds",
    stock: 7,
    tags: ["popular"],
    rating: 4.8,
    reviewCount: 113,
    specifications: [
      { label: "Size", value: "Queen" },
      { label: "Material", value: "Solid Sheesham wood" },
    ],
  },
  {
    title: "Regal Heritage Bed",
    slug: "regal-heritage-bed",
    shortDescription: "Decorative carved bed frame with statement headboard.",
    description:
      "An ornate bed design inspired by classic craftsmanship, perfect for premium master bedrooms.",
    price: 134.99,
    compareAtPrice: 199.99,
    image: "/assets/crops/collection-bed.jpg",
    gallery: ["/assets/crops/collection-bed.jpg"],
    categorySlug: "beds",
    stock: 5,
    tags: ["popular"],
    rating: 4.9,
    reviewCount: 94,
    specifications: [
      { label: "Style", value: "Traditional carved frame" },
      { label: "Color", value: "Deep walnut" },
    ],
  },
  {
    title: "Ivory Manor Bed",
    slug: "ivory-manor-bed",
    shortDescription: "Two-tone bed with upholstered headboard accent.",
    description:
      "Combining rustic texture with soft upholstery, this bed adds comfort and elegance to modern homes.",
    price: 134.99,
    compareAtPrice: 174.99,
    image: "/assets/crops/collection-bed.jpg",
    gallery: ["/assets/crops/collection-bed.jpg"],
    categorySlug: "beds",
    stock: 8,
    tags: ["popular"],
    rating: 4.6,
    reviewCount: 57,
    specifications: [
      { label: "Size", value: "King" },
      { label: "Headboard", value: "Padded fabric panel" },
    ],
  },
];

const blogPosts = [
  {
    title: "Designing Luxury Bedrooms with Warm Wood Tones",
    slug: "designing-luxury-bedrooms-with-warm-wood-tones",
    excerpt:
      "Discover how layered lighting and handcrafted wood furniture can transform your sleeping space.",
    content:
      "From selecting the right headboard profile to balancing textures in the room, this guide walks through practical styling ideas for creating a premium, restful bedroom atmosphere.",
    coverImage: "/assets/crops/latest-card-1-full.jpg",
    tags: ["interior", "bedroom", "design"],
    author: "Rustik Studio",
    isPublished: true,
  },
  {
    title: "Choosing the Right Bed Size for Urban Apartments",
    slug: "choosing-the-right-bed-size-for-urban-apartments",
    excerpt:
      "A practical checklist for selecting furniture that fits compact spaces without sacrificing comfort.",
    content:
      "Measure pathways, match bed proportions to room dimensions, and pair storage-friendly furniture to maintain visual openness in city homes.",
    coverImage: "/assets/crops/latest-card-2-full.jpg",
    tags: ["tips", "bedroom", "furniture"],
    author: "Rustik Team",
    isPublished: true,
  },
  {
    title: "Modern Rustic Furniture Trends for 2026",
    slug: "modern-rustic-furniture-trends-for-2026",
    excerpt:
      "Explore trending wood finishes, minimalist forms, and handcrafted details shaping this year.",
    content:
      "The 2026 trend map highlights tonal consistency, modular pieces, and authentic materials that create calm, grounded interiors.",
    coverImage: "/assets/crops/latest-card-3-full.jpg",
    tags: ["trends", "living", "decor"],
    author: "Editorial Desk",
    isPublished: true,
  },
];

const homeContent = {
  hero: {
    title: "Wave Lounge Chair",
    description:
      "This is Photoshop's version of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.",
    cta: "ADD TO CART",
    image: "/assets/crops/hero-chair.jpg",
    highlightPrice: 129.99,
  },
  hotDeals: [
    {
      title: "Elite Collection",
      subtitle: "Design Furniture",
      image: "/assets/crops/hotdeal-left-full.jpg",
      discount: "35%",
    },
    {
      title: "Reclaimed and Hand Crafted",
      subtitle: "Sale Off",
      image: "/assets/crops/hotdeal-right-full.jpg",
      discount: "50%",
    },
  ],
  buyStripImage: "/assets/crops/buy-strip-full.jpg",
  partnerStripImage: "/assets/crops/partners-full.jpg",
};

module.exports = {
  categories,
  products,
  blogPosts,
  homeContent,
};
